name: Ping Servers

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl both health endpoints
        run: |
          curl https://booknest-1-vowm.onrender.com/health
          curl https://booknest-production-25a6.up.railway.app/health
